# General Configuration
mode: 'train'  # Can be 'train', 'backtest', 'optimize', or 'live_trading'

# Data Configuration
asset: 'BTC/USD'
timeframes: ['5m', '15m', '1h', '1d']
sequence_length: 100

# Model Configuration
input_size: 39  # Update this to match the number of features we're actually generating
hidden_size: 40  # Set this to be divisible by num_heads
num_layers: 2
num_heads: 4
output_size: 1
learning_rate: 0.001
batch_size: 32
num_epochs: 100

# Training Configuration
model_save_path: 'model_params.pth'
model_state_path: 'model_state.pth'
device: 'cpu'  # Change to 'cuda' if GPU is available

# Optimization Configuration
optimization_iterations: 50

# Trading Configuration
entry_threshold: 0.5
exit_threshold: 0.3
stop_loss: 0.02
take_profit: 0.05
max_position_size: 0.1

# Risk Management
risk_per_trade: 0.01
max_daily_loss: 0.05
circuit_breaker_threshold: 0.1
circuit_breaker_pause_time: 3600  # in seconds

# Live Trading Configuration
exchange: 'binance'  # Use the appropriate exchange name from ccxt
api_key: 'your_api_key_here'
api_secret: 'your_api_secret_here'
trading_interval: 300  # in seconds
trade_log_file: 'trade_log.csv'

# Logging Configuration
log_level: 'INFO'
log_file: 'trading_log.txt'
